CC=g++
LD=g++
TARGET=a.exe
SOURCES = test.cpp vec.h
OBJECTS := $(SOURCES:%.cpp=%.o)
INCL=-I../alg/ -I../exception -I../../tinylog/src
CFLAGS=-c -Os -fno-rtti -Wall
LFLAGS=
APPLIBS=

all: $(TARGET)

#  Make target
$(TARGET): $(OBJECTS) $(APPLIBS)
	$(LD) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(APPLIBS) $(SYSLIBS) tinylog.a

#  Make objects
%.o: %.cpp
	$(CC) $(CFLAGS) $< -o $@ $(INCL)

#  Clean
.PHONY : clean
clean :
	-rm $(TARGET) $(OBJECTS)
